// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetTerraformGraph(arg1:string):Promise<models.GraphPayload>;

export function SelectDirectory():Promise<string>;
